### ISSUE TITLE
dev-deployment is down

### ISSUE THREAD

**Issue by Levino** [bakdata/conquery#1260]
The [dev deployment](https://conquery-dev.herokuapp.com/app/static) has issues. It is the official url of this project. See screenshot. Maybe one wants to use a link to the ["prod?" deployment](https://conquery.herokuapp.com/app/static/) there. That one is working as it looks to me.
![Selection_353](https://user-images.githubusercontent.com/1150767/87165065-e7b78300-c2c9-11ea-9328-5118f4ab1ead.jpg)

**Comment by awildturtok** [comment]
The dev/prod deployment is handled by @martintaraz. IIRC the "prod" deployment only uses debugging data while the "dev" deployment uses a publicly available medical dataset (ie our target domain).

**Comment by jakobkolb** [comment]
Apparently, both the dev and the prod deployments are down atm. :shrug:

**Comment by awildturtok** [comment]
We've investigated this situation and concldued that neither of these deployments have been maintained since their initial setup, we've therefore decided to unlist them and restructure this setup in the future. Sorry for the inconvenience.
