### ISSUE TITLE
Typescript code does not build without errors

### ISSUE THREAD

**Issue by Levino** [bakdata/conquery#1262]
When I try to run `yarn start` I get a lot of typescript errors in the console. It looks like the webserver with the react app is running anyhow, which is a bit surprising.

**Comment by Levino** [comment]
So running `yarn typecheck` results in 1831 errors.

The command `yarn typecheck` should be run in CI and block PRs from being merged if failling.

**Comment by awildturtok** [comment]
Hi Levino, thanks for your suggestions!

The change to Typescript was (Afaik) meant to be a step by step migration instead of a complete makeover. The frontend is as of yet not integrated into our backend pipeline.

**Comment by Levino** [comment]
A transition is in order. Ignoring typescript errors however is not. You want to go easy on the screws and tighten them one after the other. But once any screw is fixed, any error caused by it must block code from being merged.

For example in this case here one could set `implicitAny` to `true` and turn a lot of the errors into warnings. But a non-existent import would still be an error (which must be an error because if I import something which does not exist that is worse than not importing anything! And these errors currently exist, see #1267).

So I suggest to relax the rules for typescript and fix the errors that are still reported until only warnings are reported and then step by step tighten the rules and fix the then warnings-turned-errors. Btw: Fixing most of the errors (90%) should be doable in an hour or so because it is mostly about missing types.

**Comment by Levino** [comment]
And one question remains which could potentially be answered by @Kadrian: Why is it possible to build? Does the typescript step run with `transpileOnly`? Why do these errors not block the build?

**Comment by awildturtok** [comment]
https://github.com/bakdata/conquery/blob/develop/frontend-resources/pom.xml#L63

This POM documents the steps we take to build and package our frontend maybe that might help?

For testing purposes I usually run `yarn` then `yarn start` which is sufficient.

**Comment by Levino** [comment]
So this is what I get for the build:
```bash
$ yarn build
yarn run v1.22.4                                                                                                                                                                                                  
$ react-app-rewired build                                                                                                                                                                                         
Creating an optimized production build...
Browserslist: caniuse-lite is outdated. Please run next command `yarn upgrade`
Browserslist: caniuse-lite is outdated. Please run next command `yarn upgrade`
Browserslist: caniuse-lite is outdated. Please run next command `yarn upgrade`
Browserslist: caniuse-lite is outdated. Please run next command `yarn upgrade`
Browserslist: caniuse-lite is outdated. Please run next command `yarn upgrade`
Browserslist: caniuse-lite is outdated. Please run next command `yarn upgrade`
Compiled with the following type errors (you may want to check these before deploying your app):

/home/levin/coding/hardfork/conquery/frontend/src/index.ts
TypeScript error in /home/levin/coding/hardfork/conquery/frontend/src/index.ts(23,32):
Argument of type 'Locale' is not assignable to parameter of type 'AvailableLocale'.
  Type 'Locale' is not assignable to type '"de"'.  TS2345

    21 | 
    22 | if (!LANG || LANG === "de") {
  > 23 |   initializeLocalization("de", de, translationsDe);
       |                                ^
    24 | } else {
    25 |   initializeLocalization("en", enGB, translationsEn);
    26 | }


Done in 44.33s.
```
So exit code is 0. The typescript errors do (by default) not prevent webpack from producing an output. This output however might be broken as advised by webpack. Ignoring this is very dangerous! The errors should be fixed or turned into warnings so actual errors can be caught in the future.

Also you should read up on [how to use `create-react-app` in CI](https://create-react-app.dev/docs/running-tests/#continuous-integration). Baseline: You do not need to run `yarn --watchAll=false` and `yarn --frozen-lockfile` etc. when you set the environment on your CI-machine right.

Also you should always use [permalinks](https://docs.github.com/en/github/managing-files-in-a-repository/getting-permanent-links-to-files) like so:
https://github.com/bakdata/conquery/blob/05a3f0eaf7801728852f6a412c42ec256e228342/frontend-resources/pom.xml#L63-L101
The reason for that is that the file will change in the branch `development` and then the context for our little conversation here will be lost and it will not make sense to anyone any more.

**Comment by awildturtok** [comment]
I have fixed some small issues but as the frontend's code is not my domain i cannot go into too much depth. 

Your feedback on the CI was pretty good, thank you! I will look into integrating it in time.
