### ISSUE TITLE
What is the password?

### ISSUE THREAD

**Issue by Levino** [bakdata/conquery#1263]
When I start the dev server I am redirected to /login. What is the password? Could not find it in the Readme and it is a bit tidious to reverse engineer it from the source...
![Selection_357](https://user-images.githubusercontent.com/1150767/87170884-3d902900-c2d2-11ea-9f9d-5f90310c130d.jpg)

**Comment by Levino** [comment]
Since this is a demo any value should be accepted anyhow. What is the point of checking this?

**Comment by Levino** [comment]
Found it!
https://github.com/bakdata/conquery/blob/e99591a352b0443ac3e6ab4bfd0c90dcc55b5e29/frontend/mock-api/index.js#L352

**Comment by thoniTUB** [comment]
Hey Levino,
You can also disable the Login, according to #1010 .
Since the build changed to `create-react-app` I suppose the environment variable might be prefixed with a `REACT_APP_`.

**Comment by Levino** [comment]
[Interesting conversation](https://github.com/bakdata/conquery/pull/1010#issuecomment-579653502).

People tend to expect a description for this kind of usage and behavior from the docs / the README. It should have been added by #1010. You can merge #1266 to fix this. A follow up PR should document the feature-switch via the environment variable you mentioned.
