### ISSUE TITLE
Better DatePicker

### ISSUE THREAD

**Issue by manuel-hegner** [bakdata/conquery#21]
The current DatePicker is a typical HTML solution. Our case is a bit more specific though. First of all our users often only wanto to select a year, quarter or month and not a specific date. On the other hand they want to select their month quickly because they may have to use the date picker a lot.

Maybe something like the windows system clock calender selection would work best for us?

**Comment by nstrelow** [comment]
react-datepicker is used in DateRangePicker and QueryGroupModal

**Comment by nstrelow** [comment]
react-datepicker received a lot of updates since our version. All supported methods right now can be found here: https://reactdatepicker.com/

Interesting for us would be the option to have a Month and Year dropdown. With this it would be faster to select it.

**Comment by MarcusBaitz** [comment]
The enhancement in #144 improved the input.
