### ISSUE TITLE
Enable hot reloading for external forms

### ISSUE THREAD

**Issue by rs22** [bakdata/conquery#37]
Currently, changing an external form (e.g. the ExampleForm in the demo app) forces a full-page reload. I guess this is because external forms don't live under the AppRoot but are `require`d earlier during application startup.

We should investigate if it's possible to also enable hot reloading for them.

**Comment by nstrelow** [comment]
Currently hot reloading lives in the as a wrapping component in AppRoot.
But the .babelrc and webpack.config needs adjustment to make it work on projects using conquery.
