### ISSUE TITLE
Heroku deployment with docker images

### ISSUE THREAD

**Issue by nstrelow** [bakdata/conquery#41]
Deploy Docker images to Heroku for master and develop.
Show both links in Readme.

Also show build status of both.

**Comment by rs22** [comment]
Something I already found out towards this end:
We have to adjust the Dockerfile's CMD entry, to not overwrite Heroku's PORT environment variable, e.g.:
`CMD cd /conquery && NODE_ENV=production node app/server`

We also have to set a publicPath in the webpack.production.config.js (this is independent from Heroku, I actually assumed that I had fixed this already...)
`publicPath: '/'`
