### ISSUE TITLE
Query can't be deleted

### ISSUE THREAD

**Issue by Kadrian** [bakdata/conquery#441]
<img width="347" alt="Bildschirmfoto 2019-03-12 um 17 38 37" src="https://user-images.githubusercontent.com/1403093/54218550-1a8f1280-44ee-11e9-8c5a-d4f3bbb85108.png">

Looks good, getting 204 No Content.

But the next time the queries are requested, the deleted query is still there.

**Comment by awildturtok** [comment]
The deletion has not yet been implemented.

I can look into it. If I don't manage to do it, I will ask @thoniTUB to take care of it as he created the original issue.

**Comment by awildturtok** [comment]
https://github.com/bakdata/conquery/issues/239

**Comment by awildturtok** [comment]
https://github.com/bakdata/conquery/pull/445

Can you test if this patch is sufficient?

**Comment by Kadrian** [comment]
Works!
