### ISSUE TITLE
GET on a query should not return Integer min / max when no filter was entered

### ISSUE THREAD

**Issue by Kadrian** [bakdata/conquery#458]
## Expected behavior
`min` / `max` is empty or null when not entered by the user

## Actual behavior
`min` / `max` is `-9223372036854776000` / `9223372036854776000`

## Steps to reproduce
- Add a concept (with a range filter) to the editor
- Run query
- Clear the editor
- Find the previous query, drag it to the editor
- Hit expand
- Check the expanded node's filter properties
- See the large numbers

**Comment by manuel-hegner** [comment]
That happens because we represent date ranges as epoch days and represent open ended results with the minimum and maximum number in min and max.

serialization should (after a fix) handle this and print null while output should render with ∞.
