### ISSUE TITLE
Clarify search in backend

### ISSUE THREAD

**Issue by Kadrian** [bakdata/conquery#493]
**Current state in `ConceptSearch.java`**
- Virtual concepts: additional infos are `NOT` searched in
- Virtual concepts: Whatever is returned from `getName` is additionally searched in

My questions:
- Do virtual concepts not have additional infos? If they do, should searching over additional infos be added in this case?
- What is returned by `getName` and how is it different from what's returned in `getLabel`? Can the search over `getName` be removed?

**Comment by awildturtok** [comment]
The search needs a big overhaul anyway: https://github.com/bakdata/conquery/issues/469 additionally it needs to be updated more often than just on startup which I will be doing the coming weeks. I will take care of this after my current tasks are finished.

**Comment by Kadrian** [comment]
Closing this in favor of https://github.com/bakdata/conquery/pull/516
