### ISSUE TITLE
Return saved query label for stored queries

### ISSUE THREAD

**Issue by Kadrian** [bakdata/conquery#539]
At the moment, query labels are not returned from 
```
GET /datasets/:datasetId/stored-queries/:id
```
for `SAVED_QUERY`.

That means, when I expand a query that contains another renamed query, the renamed label is not returned.

Example

```
      "type": "CONCEPT_QUERY",
      "root": {
        "type": "AND",
        "children": [
          {
            "type": "OR",
            "children": [
              {
                "type": "SAVED_QUERY",
                "query": "datasetId.b4532bca$2d5086$2d43e9$2d96e0$2d28b2ba5bde52",
                // I WOULD EXPECT A LABEL HERE
                "resolvedQuery": {
                  "type": "CONCEPT_QUERY",
                  "root": {
```

**Comment by manuel-hegner** [comment]
Mhh. That is a bit complicated. We do not resolve this for anything. It should look like:
```json
"type": "CONCEPT_QUERY",
      "root": {
        "type": "AND",
        "children": [
          {
            "type": "OR",
            "children": [
              {
                "type": "SAVED_QUERY",
                "query": "datasetId.b4532bca$2d5086$2d43e9$2d96e0$2d28b2ba5bde52",
```
The `resolvedQuery` field is an error in and of itself and will only appear randomly in this location. It should be an internal field. The whole node is only a container around the target id and should not hold other information.

**Comment by Kadrian** [comment]
Okay. Well how would you suggest to resolve the query then, including the label?

**Comment by manuel-hegner** [comment]
The frontend for the old backend would simply create a new request for the saved query if that one is expanded

**Comment by Kadrian** [comment]
Hmm, alright, I'll do the additional requests.
