### ISSUE TITLE
Query keeps running after stopped successfully

### ISSUE THREAD

**Issue by Kadrian** [bakdata/conquery#546]
**Expected**
When a query is stopped, the next poll will receive an answer including `status: "CANCELED"`.

**Actual**
When I stop a query successfully, (DELETE with status 204), the next poll for that query's status still returns a query object with status `RUNNING`.

**Steps to reproduce**
- Start a query that takes a long time
- Stop the query, before it's finished
- See the frontend continue polling the results in the network tab, because the status is still `RUNNING`

**Comment by Kadrian** [comment]
This isn't working yet, right?

**Comment by awildturtok** [comment]
Ist jetzt implementiert :D
